//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class assembly_line_master
    {
        public long assembly_line_id { get; set; }
        public string assembly_line_no { get; set; }
        public string assembly_line_name { get; set; }
        public Nullable<short> assembly_line_type { get; set; }
        public Nullable<long> FKPlant_id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
