//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defect_comment
    {
        public long Defect_comment_id { get; set; }
        public long FKDefect_id { get; set; }
        public Nullable<long> FKUser_id { get; set; }
        public string comment { get; set; }
        public string defect_resolution_attach { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    }
}
