//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class defect
    {
        public long defect_id { get; set; }
        public string attachments { get; set; }
        public string defect_desc { get; set; }
        public Nullable<bool> status { get; set; }
        public string title { get; set; }
        public Nullable<bool> IsLBM { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public string createdBy { get; set; }
        public Nullable<long> FKinspection_parameter_id { get; set; }
        public Nullable<long> FKtractor_id { get; set; }
        public string time_spent { get; set; }
        public Nullable<bool> IsWarranty { get; set; }
        public string DefectGroup { get; set; }
        public string DefectCode { get; set; }
        public string TaskGroup { get; set; }
        public string TaskCode { get; set; }
        public string NotificationNo { get; set; }
        public string NotificationType { get; set; }
        public Nullable<System.DateTime> NotificationDateTime { get; set; }
        public string Vendor { get; set; }
        public Nullable<short> Item { get; set; }
        public Nullable<short> DefectType { get; set; }
        public Nullable<short> SyncStatus { get; set; }
        public string TaskAction { get; set; }
        public Nullable<bool> IsShipping { get; set; }
        public string BulletinNo { get; set; }
        public string BulletinPdfLink { get; set; }
        public string BulletinType { get; set; }
        public string CampaignName { get; set; }
        public string CampaignReleaseDate { get; set; }
        public Nullable<bool> IsPriority { get; set; }
        public string SAPDefectMaterialCode { get; set; }
    }
}
