//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class despatch_closure_master
    {
        public long despatch_closure_id { get; set; }
        public string despatch_closure_reason { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
