//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class inspection_parameter_master
    {
        public long inspection_parameter_id { get; set; }
        public string inspection_parameter_name { get; set; }
        public string inspection_parameter_desc { get; set; }
        public Nullable<long> FKinspection_type_id { get; set; }
        public string Group_Code { get; set; }
        public Nullable<int> createdById { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> modifiedById { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    }
}
