//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection_Test_Details
    {
        public long inspection_id { get; set; }
        public Nullable<long> FKinspection_parameter_id { get; set; }
        public string status { get; set; }
        public Nullable<long> FKtractor_id { get; set; }
        public Nullable<bool> IsLBM { get; set; }
        public string createdBy { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<bool> IsShipping { get; set; }
    }
}
