//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class mechanic_tractor_mapping
    {
        public int mechanic_tractor_mapping_id { get; set; }
        public Nullable<long> tractor_id { get; set; }
        public Nullable<long> user_id { get; set; }
        public Nullable<int> createdById { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> modifiedById { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
    }
}
