//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class performby_test
    {
        public int performby_test_id { get; set; }
        public Nullable<int> task_id { get; set; }
        public Nullable<int> tracktor_id { get; set; }
        public string initial { get; set; }
        public Nullable<int> createdById { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> modifiedById { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public int dyno_test_id { get; set; }
    
        public virtual task_master task_master { get; set; }
    }
}
