//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class planned_order_master
    {
        public long Planned_order_id { get; set; }
        public string Planned_order_no { get; set; }
        public string Production_order_no { get; set; }
        public string Material_code { get; set; }
        public string Material_desc { get; set; }
        public string Supply_type { get; set; }
        public Nullable<System.DateTime> Confirmed_start_date { get; set; }
        public string Demand_type { get; set; }
        public string Demand_order_no { get; set; }
        public Nullable<System.DateTime> Demand_date { get; set; }
        public Nullable<long> FKPlant_id { get; set; }
        public Nullable<short> Planned_order_type { get; set; }
        public Nullable<short> Assembly_type { get; set; }
        public string Sales_order_no { get; set; }
        public Nullable<long> FKSales_order_id { get; set; }
        public Nullable<long> FKLinenumber_id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
