//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales_order_master
    {
        public long sales_order_id { get; set; }
        public string sales_order_no { get; set; }
        public string sales_order_date { get; set; }
        public string sales_type { get; set; }
        public string material_code { get; set; }
        public string material_desc { get; set; }
        public Nullable<long> FKPlant_id { get; set; }
        public string Sold_To_Party_Code { get; set; }
        public string Sold_To_Party_Name { get; set; }
        public Nullable<int> order_qty { get; set; }
        public Nullable<int> fulfil_qty { get; set; }
        public string bo_qty { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string approval_status { get; set; }
        public string carrier { get; set; }
        public string invoice { get; set; }
        public string ship_date { get; set; }
        public string invoice_date { get; set; }
        public string actual_ship_date { get; set; }
        public string order_type { get; set; }
        public string req_del_date { get; set; }
        public string state { get; set; }
        public Nullable<long> FkDespatch_closure_id { get; set; }
        public string Order_Reason { get; set; }
        public string Ship_To_Party_Code { get; set; }
        public string Ship_To_Party_Name { get; set; }
        public string Special_INST { get; set; }
        public string Sent_To_Inspection_date { get; set; }
        public string EOM { get; set; }
        public Nullable<bool> IsUnserializeSalesOrder { get; set; }
        public string Ship_To_City { get; set; }
        public string Finance_Company { get; set; }
        public string Net_Price { get; set; }
        public string Currency { get; set; }
    }
}
