//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class sop_document_master
    {
        public long SopDocument_id { get; set; }
        public Nullable<System.DateTime> Sop_start_date { get; set; }
        public Nullable<System.DateTime> Sop_end_date { get; set; }
        public string Sop_file_extension { get; set; }
        public string Sop_file_type { get; set; }
        public Nullable<short> Sop_status { get; set; }
        public Nullable<long> FKPlant_id { get; set; }
        public Nullable<long> FKPart_id { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
