//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class tireType_Group_mapping
    {
        public long tireType_Group_mapping_id { get; set; }
        public Nullable<long> FKtire_type_id { get; set; }
        public string FKProduct_Group { get; set; }
        public string LL_RR { get; set; }
        public string LF_RF { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    }
}
