//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class tractor_master
    {
        public long tractor_id { get; set; }
        public string prod_order_no { get; set; }
        public string material_no { get; set; }
        public Nullable<long> Fkplant_id { get; set; }
        public Nullable<decimal> hours { get; set; }
        public string tire_brand { get; set; }
        public string tire_type { get; set; }
        public string engine_sr_no { get; set; }
        public string cab_sr_no { get; set; }
        public string loader_sr_no { get; set; }
        public string backhoe_sr_no { get; set; }
        public string mower_sr_no { get; set; }
        public string production_attach_URL { get; set; }
        public string remarks { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> createdById { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> modifiedById { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<System.DateTime> tractor_date { get; set; }
        public string goodsIssueNo { get; set; }
        public string goodsReceipt { get; set; }
        public string invoiceNo { get; set; }
        public string salesOrderNo { get; set; }
        public string serialNo { get; set; }
        public string backhoeMaterialNo { get; set; }
        public string cabMaterialNo { get; set; }
        public string loaderMaterialNo { get; set; }
        public string mowerMaterialNo { get; set; }
        public Nullable<int> defect_status { get; set; }
        public Nullable<bool> IsLoaderAttach { get; set; }
        public Nullable<bool> IsBackHoeAttach { get; set; }
        public Nullable<bool> IsMowerAttach { get; set; }
        public Nullable<bool> IsCabinAttach { get; set; }
        public string productionNote { get; set; }
        public Nullable<bool> IsAssemblyDone { get; set; }
        public Nullable<bool> IsLBMDone { get; set; }
        public string ROPS { get; set; }
        public Nullable<bool> IsDynoTestRequired { get; set; }
        public string InvoiceDate { get; set; }
        public string kitSerialNo { get; set; }
        public Nullable<long> FKSales_order_id { get; set; }
        public Nullable<System.DateTime> tractor_date_LBM { get; set; }
        public Nullable<bool> IsShippingDone { get; set; }
        public Nullable<System.DateTime> tractor_date_Shipping { get; set; }
        public Nullable<System.DateTime> StartInspectionDateTime { get; set; }
        public Nullable<System.DateTime> EndInspectionDateTime { get; set; }
    }
}
