//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelRead
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_master
    {
        public long user_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public Nullable<long> FKuser_type_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string contact_no { get; set; }
        public Nullable<long> Fkplant_id { get; set; }
        public string email_id { get; set; }
        public string designation { get; set; }
        public Nullable<int> createdById { get; set; }
        public Nullable<System.DateTime> createdDate { get; set; }
        public Nullable<int> modifiedById { get; set; }
        public Nullable<System.DateTime> modifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual user_type_master user_type_master { get; set; }
    }
}
