//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOQtyUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetRolePermission
    {
        public string Id { get; set; }
        public string RoleId { get; set; }
        public int PermissionId { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual Permission Permission { get; set; }
    }
}
