//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOQtyUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocNumber
    {
        public int Id { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public string Number { get; set; }
        public Nullable<System.DateTime> DocNumberDate { get; set; }
        public Nullable<int> DocNumberTypeId { get; set; }
        public Nullable<System.DateTime> BillingDate { get; set; }
        public string PortalOrderNumber { get; set; }
        public Nullable<System.DateTime> CommInvoiceDate { get; set; }
        public string OrderMaterial { get; set; }
        public Nullable<long> OrderQuantity { get; set; }
        public string InvoiceMaterial { get; set; }
        public Nullable<long> InvoiceQty { get; set; }
        public Nullable<long> InvoiceNetValue { get; set; }
        public string InvoiceNumber { get; set; }
        public string Currency { get; set; }
        public string BOL { get; set; }
        public string CourierDetails { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<System.DateTime> PortalOrderDate { get; set; }
        public string OrderType { get; set; }
        public string OrderStatus { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public string DeliveryItemNo { get; set; }
        public string VinNo { get; set; }
        public string SalesOrg { get; set; }
        public string MaterialNo { get; set; }
        public Nullable<System.DateTime> MaterialAvailabilityDate { get; set; }
        public Nullable<long> DeliveryQuantity { get; set; }
        public string Volume { get; set; }
        public string VolumeUnit { get; set; }
    
        public virtual DocNumberType DocNumberType { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
