//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOQtyUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldStepRoleVisibility
    {
        public int FieldId { get; set; }
        public int StepId { get; set; }
        public string VisibilityType { get; set; }
        public string RoleId { get; set; }
        public int Id { get; set; }
    
        public virtual AspNetRole AspNetRole { get; set; }
        public virtual FormField FormField { get; set; }
        public virtual Step Step { get; set; }
    }
}
