//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOQtyUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderItem()
        {
            this.Chats = new HashSet<Chat>();
            this.Containers = new HashSet<Container>();
            this.DocNumbers = new HashSet<DocNumber>();
            this.StatusesTracks = new HashSet<StatusesTrack>();
            this.Vins = new HashSet<Vin>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public Nullable<int> PlantId { get; set; }
        public string Model { get; set; }
        public Nullable<int> Category { get; set; }
        public string Description { get; set; }
        public int ESOQty { get; set; }
        public string Batch { get; set; }
        public System.DateTime ESODate { get; set; }
        public string PONo { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<int> OpenOrder { get; set; }
        public Nullable<int> Feasible { get; set; }
        public Nullable<int> Gap { get; set; }
        public string Remarks { get; set; }
        public Nullable<System.DateTime> LikelyDateOfDispatch { get; set; }
        public Nullable<System.DateTime> LikelyDateOfShipment { get; set; }
        public string VesselDate { get; set; }
        public string PaymentMode { get; set; }
        public Nullable<System.DateTime> ExpectedPaymentDate { get; set; }
        public string CurrentPaymentStatus { get; set; }
        public Nullable<System.DateTime> ActualDateOfDispatch { get; set; }
        public Nullable<System.DateTime> ActualDateOfShipment { get; set; }
        public Nullable<int> ShipmentModeId { get; set; }
        public string EstimatedTransitTime { get; set; }
        public Nullable<System.DateTime> DatePP { get; set; }
        public string SpecialApprovalRemark { get; set; }
        public string PaymentRemark { get; set; }
        public bool ApprovalForDispatch { get; set; }
        public string PIDoc { get; set; }
        public string LCDoc { get; set; }
        public string AdvDoc { get; set; }
        public string VinNos { get; set; }
        public string ContainerNos { get; set; }
        public string PINo { get; set; }
        public bool CustomInvoiceNumber { get; set; }
        public bool CommercialInvoiceNumber { get; set; }
        public bool DeliveryNumber { get; set; }
        public bool BOL { get; set; }
        public bool CourierDetails { get; set; }
    
        public virtual Category Category1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Chat> Chats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Container> Containers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DocNumber> DocNumbers { get; set; }
        public virtual Order Order { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ShipmentMode ShipmentMode { get; set; }
        public virtual Step Step { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusesTrack> StatusesTracks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vin> Vins { get; set; }
    }
}
