//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOQtyUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusesTrack
    {
        public int Id { get; set; }
        public Nullable<int> OrderItemId { get; set; }
        public Nullable<int> StepId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string UserId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual OrderItem OrderItem { get; set; }
        public virtual Step Step { get; set; }
    }
}
