//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOQtyUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserChatUnreadCount
    {
        public string UserId { get; set; }
        public int ChatId { get; set; }
        public int UnreadCount { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Chat Chat { get; set; }
    }
}
