//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOQtyUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserUtilization
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public Nullable<System.DateTime> LogoutDateTime { get; set; }
        public Nullable<long> LoginCount { get; set; }
        public Nullable<short> LoginStatus { get; set; }
        public Nullable<short> LogOutStatus { get; set; }
        public Nullable<short> ProjectType { get; set; }
        public string MobileEvent { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
