//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESOQtyUpdate
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vin
    {
        public int Id { get; set; }
        public int OrderItemId { get; set; }
        public Nullable<int> ContainerId { get; set; }
        public string VIN1 { get; set; }
    
        public virtual Container Container { get; set; }
        public virtual OrderItem OrderItem { get; set; }
    }
}
